blueprints/admin.py
import json
from collections import defaultdict
from datetime import datetime
from datetime import timedelta
from datetime import timezone
from typing import Any
from typing import List
from urllib.parse import urlparse

import flask
from flask import abort
from flask import current_app as app
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from little_boxes import activitypub as ap
from little_boxes.webfinger import get_actor_url
from passlib.hash import bcrypt
from u2flib_server import u2f

import config
from config import DB
from config import ID
from config import PASS
from core.activitypub import Box
from core.activitypub import _meta
from core.activitypub import post_to_outbox
from core.db import find_one_activity
from core.meta import by_object_id
from core.meta import by_object_visibility
from core.meta import by_remote_id
from core.meta import by_type
from core.meta import follow_request_accepted
from core.meta import in_outbox
from core.meta import not_deleted
from core.meta import not_poll_answer
from core.meta import not_undo
from core.shared import MY_PERSON
from core.shared import _build_thread
from core.shared import _Response
from core.shared import csrf
from core.shared import htmlify
from core.shared import login_required
from core.shared import noindex
from core.shared import p
from core.shared import paginated_query
from utils import now
from utils.emojis import EMOJIS_BY_NAME
from utils.lookup import lookup

blueprint = flask.Blueprint("admin", __name__)


def verify_pass(pwd):
    return bcrypt.verify(pwd, PASS)


@blueprint.route("/admin/update_actor")
@login_required
def admin_update_actor() -> _Response:
    # FIXME(tsileo): make this a task, and keep track of our own actor_hash at startup
    update = ap.Update(
        actor=MY_PERSON.id,
        object=MY_PERSON.to_dict(),
        to=[MY_PERSON.followers],
        cc=[ap.AS_PUBLIC],
        published=now(),
    )

    post_to_outbox(update)
    return "OK"


@blueprint.route("/admin/logout")
@login_required
def admin_logout() -> _Response:
    session["logged_in"] = False
    return redirect("/")


@blueprint.route("/login", methods=["POST", "GET"])
@noindex
def admin_login() -> _Response:
    if session.get("logged_in") is True:
        return redirect(url_for("admin.admin_notifications"))

    devices = [doc["device"] for doc in DB.u2f.find()]
    u2f_enabled = True if devices else False
    if request.method == "POST":
        csrf.protect()
        # 1. Check regular password login flow
        pwd = request.form.get("pass")
        if pwd:
            if verify_pass(pwd):
                session.permanent = True
                session["logged_in"] = True
                return redirect(
                    request.args.get("redirect") or url_for("admin.admin_notifications")
                )
            else:
                abort(403)
        # 2. Check for U2F payload, if any
        elif devices:
            resp = json.loads(request.form.get("resp"))  # type: ignore
            try:
                u2f.complete_authentication(session["challenge"], resp)
            except ValueError as exc:
                print("failed", exc)
                abort(403)
                return
            finally:
                session["challenge"] = None

            session.permanent = True
            session["logged_in"] = True
            return redirect(
                request.args.get("redirect") or url_for("admin.admin_notifications")
            )
        else:
            abort(401)

    payload = None
    if devices:
        payload = u2f.begin_authentication(ID, devices)
        session["challenge"] = payload

    return htmlify(
        render_template("login.html", u2f_enabled=u2f_enabled, payload=payload)
    )


@blueprint.route("/admin", methods=["GET"])
@login_required
def admin_index() -> _Response:
    q = {
        "meta.deleted": False,
        "meta.undo": False,
        "type": ap.ActivityType.LIKE.value,
        "box": Box.OUTBOX.value,
    }
    col_liked = DB.activities.count(q)

    return htmlify(
        render_template(
            "admin.html",
            instances=list(DB.instances.find()),
            inbox_size=DB.activities.count({"box": Box.INBOX.value}),
            outbox_size=DB.activities.count({"box": Box.OUTBOX.value}),
            col_liked=col_liked,
            col_followers=DB.activities.count(
                {
                    "box": Box.INBOX.value,
                    "type": ap.ActivityType.FOLLOW.value,
                    "meta.undo": False,
                }
            ),
            col_following=DB.activities.count(
                {
                    "box": Box.OUTBOX.value,
                    "type": ap.ActivityType.FOLLOW.value,
                    "meta.undo": False,
                }
            ),
        )
    )


@blueprint.route("/admin/indieauth", methods=["GET"])
@login_required
def admin_indieauth() -> _Response:
    return htmlify(
        render_template(
            "admin_indieauth.html",
            indieauth_actions=DB.indieauth.find().sort("ts", -1).limit(100),
        )
    )


@blueprint.route("/admin/tasks", methods=["GET"])
@login_required
def admin_tasks() -> _Response:
    return htmlify(
        render_template(
            "admin_tasks.html",
            success=p.get_success(),
            dead=p.get_dead(),
            waiting=p.get_waiting(),
            cron=p.get_cron(),
        )
    )


@blueprint.route("/admin/lookup", methods=["GET"])
@login_required
def admin_lookup() -> _Response:
    data = None
    meta = None
    follower = None
    following = None
    if request.args.get("url"):
        data = lookup(request.args.get("url"))  # type: ignore
        if data:
            if not data.has_type(ap.ACTOR_TYPES):
                meta = _meta(data)
            else:
                follower = find_one_activity(
                    {
                        "box": "inbox",
                        "type": ap.ActivityType.FOLLOW.value,
                        "meta.actor_id": data.id,
                        "meta.undo": False,
                    }
                )
                following = find_one_activity(
                    {
                        **by_type(ap.ActivityType.FOLLOW),
                        **by_object_id(data.id),
                        **not_undo(),
                        **in_outbox(),
                        **follow_request_accepted(),
                    }
                )

            if data.has_type(ap.ActivityType.QUESTION):
                p.push(data.id, "/task/fetch_remote_question")

        print(data)
        app.logger.debug(data.to_dict())
    return htmlify(
        render_template(
            "lookup.html",
            data=data,
            meta=meta,
            follower=follower,
            following=following,
            url=request.args.get("url"),
        )
    )


@blueprint.route("/admin/profile", methods=["GET"])
@login_required
def admin_profile() -> _Response:
    if not request.args.get("actor_id"):
        abort(404)

    actor_id = request.args.get("actor_id")
    actor = ap.fetch_remote_activity(actor_id)
    q = {
        "meta.actor_id": actor_id,
        "box": "inbox",
        **not_deleted(),
        "type": {"$in": [ap.ActivityType.CREATE.value, ap.ActivityType.ANNOUNCE.value]},
    }
    inbox_data, older_than, newer_than = paginated_query(
        DB.activities, q, limit=int(request.args.get("limit", 25))
    )
    follower = find_one_activity(
        {
            "box": "inbox",
            "type": ap.ActivityType.FOLLOW.value,
            "meta.actor_id": actor.id,
            "meta.undo": False,
        }
    )
    following = find_one_activity(
        {
            **by_type(ap.ActivityType.FOLLOW),
            **by_object_id(actor.id),
            **not_undo(),
            **in_outbox(),
            **follow_request_accepted(),
        }
    )

    return htmlify(
        render_template(
            "stream.html",
            actor_id=actor_id,
            actor=actor.to_dict(),
            inbox_data=inbox_data,
            older_than=older_than,
            newer_than=newer_than,
            follower=follower,
            following=following,
            lists=list(DB.lists.find()),
        )
    )


@blueprint.route("/admin/thread")
@login_required
def admin_thread() -> _Response:
    oid = request.args.get("oid")
    if not oid:
        abort(404)

    data = find_one_activity({**by_type(ap.ActivityType.CREATE), **by_object_id(oid)})
    if not data:
        dat = DB.replies.find_one({**by_remote_id(oid)})
        data = {
            "activity": {"object": dat["activity"]},
            "meta": dat["meta"],
            "_id": dat["_id"],
        }

    if not data:
        abort(404)
    if data["meta"].get("deleted", False):
        abort(410)
    thread = _build_thread(data)

    tpl = "note.html"
    if request.args.get("debug"):
        tpl = "note_debug.html"
    return htmlify(render_template(tpl, thread=thread, note=data))


@blueprint.route("/admin/new", methods=["GET"])
@login_required
def admin_new() -> _Response:
    reply_id = None
    content = ""
    thread: List[Any] = []
    print(request.args)
    default_visibility = None  # ap.Visibility.PUBLIC
    if request.args.get("reply"):
        data = DB.activities.find_one({"activity.object.id": request.args.get("reply")})
        if data:
            reply = ap.parse_activity(data["activity"])
        else:
            obj = ap.get_backend().fetch_iri(request.args.get("reply"))
            data = dict(meta=_meta(ap.parse_activity(obj)), activity=dict(object=obj))
            data["_id"] = obj["id"]
            data["remote_id"] = obj["id"]
            reply = ap.parse_activity(data["activity"]["object"])
        # Fetch the post visibility, in case it's follower only

blueprints/indieauth.py
import binascii
import os
from datetime import datetime
from datetime import timedelta
from urllib.parse import urlencode

import flask
import mf2py
from flask import Response
from flask import abort
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from itsdangerous import BadSignature

from config import DB
from config import JWT
from core.shared import _get_ip
from core.shared import htmlify
from core.shared import jsonify
from core.shared import login_required

blueprint = flask.Blueprint("indieauth", __name__)


def build_auth_resp(payload):
    if request.headers.get("Accept") == "application/json":
        return jsonify(payload)
    return Response(
        status=200,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        response=urlencode(payload),
    )


def _get_prop(props, name, default=None):
    if name in props:
        items = props.get(name)
        if isinstance(items, list):
            return items[0]
        return items
    return default


def get_client_id_data(url):
    # FIXME(tsileo): ensure not localhost via `little_boxes.urlutils.is_url_valid`
    data = mf2py.parse(url=url)
    for item in data["items"]:
        if "h-x-app" in item["type"] or "h-app" in item["type"]:
            props = item.get("properties", {})
            print(props)
            return dict(
                logo=_get_prop(props, "logo"),
                name=_get_prop(props, "name"),
                url=_get_prop(props, "url"),
            )
    return dict(logo=None, name=url, url=url)


@blueprint.route("/indieauth/flow", methods=["POST"])
@login_required
def indieauth_flow():
    auth = dict(
        scope=" ".join(request.form.getlist("scopes")),
        me=request.form.get("me"),
        client_id=request.form.get("client_id"),
        state=request.form.get("state"),
        redirect_uri=request.form.get("redirect_uri"),
        response_type=request.form.get("response_type"),
        ts=datetime.now().timestamp(),
        code=binascii.hexlify(os.urandom(8)).decode("utf-8"),
        verified=False,
    )

    # XXX(tsileo): a whitelist for me values?

    # TODO(tsileo): redirect_uri checks
    if not auth["redirect_uri"]:
        abort(400)

    DB.indieauth.insert_one(auth)

    # FIXME(tsileo): fetch client ID and validate redirect_uri
    red = f'{auth["redirect_uri"]}?code={auth["code"]}&state={auth["state"]}&me={auth["me"]}'
    return redirect(red)


@blueprint.route("/indieauth", methods=["GET", "POST"])
def indieauth_endpoint():
    if request.method == "GET":
        if not session.get("logged_in"):
            return redirect(url_for("admin.admin_login", redirect=request.url))

        me = request.args.get("me")
        # FIXME(tsileo): ensure me == ID
        client_id = request.args.get("client_id")
        redirect_uri = request.args.get("redirect_uri")
        state = request.args.get("state", "")
        response_type = request.args.get("response_type", "id")
        scope = request.args.get("scope", "").split()

        print("STATE", state)
        return htmlify(
            render_template(
                "indieauth_flow.html",
                client=get_client_id_data(client_id),
                scopes=scope,
                redirect_uri=redirect_uri,
                state=state,
                response_type=response_type,
                client_id=client_id,
                me=me,
            )
        )

    # Auth verification via POST
    code = request.form.get("code")
    redirect_uri = request.form.get("redirect_uri")
    client_id = request.form.get("client_id")

    ip, geoip = _get_ip()

    auth = DB.indieauth.find_one_and_update(
        {
            "code": code,
            "redirect_uri": redirect_uri,
            "client_id": client_id,
            "verified": False,
        },
        {
            "$set": {
                "verified": True,
                "verified_by": "id",
                "verified_at": datetime.now().timestamp(),
                "ip_address": ip,
                "geoip": geoip,
            }
        },
    )
    print(auth)
    print(code, redirect_uri, client_id)

    # Ensure the code is recent
    if (datetime.now() - datetime.fromtimestamp(auth["ts"])) > timedelta(minutes=5):
        abort(400)

    if not auth:
        abort(403)
        return

    session["logged_in"] = True
    me = auth["me"]
    state = auth["state"]
    scope = auth["scope"]
    print("STATE", state)
    return build_auth_resp({"me": me, "state": state, "scope": scope})


@blueprint.route("/token", methods=["GET", "POST"])
def token_endpoint():
    # Generate a new token with the returned access code
    if request.method == "POST":
        code = request.form.get("code")
        me = request.form.get("me")
        redirect_uri = request.form.get("redirect_uri")
        client_id = request.form.get("client_id")

        now = datetime.now()
        ip, geoip = _get_ip()

        # This query ensure code, client_id, redirect_uri and me are matching with the code request
        auth = DB.indieauth.find_one_and_update(
            {
                "code": code,
                "me": me,
                "redirect_uri": redirect_uri,
                "client_id": client_id,
                "verified": False,
            },
            {
                "$set": {
                    "verified": True,
                    "verified_by": "code",
                    "verified_at": now.timestamp(),
                    "ip_address": ip,
                    "geoip": geoip,
                }
            },
        )

        if not auth:
            abort(403)

        scope = auth["scope"].split()

        # Ensure there's at least one scope
        if not len(scope):
            abort(400)

        # Ensure the code is recent
        if (now - datetime.fromtimestamp(auth["ts"])) > timedelta(minutes=5):
            abort(400)

        payload = dict(me=me, client_id=client_id, scope=scope, ts=now.timestamp())
        token = JWT.dumps(payload).decode("utf-8")
        DB.indieauth.update_one(
            {"_id": auth["_id"]},
            {
                "$set": {
                    "token": token,
                    "token_expires": (now + timedelta(minutes=30)).timestamp(),
                }
            },
        )

        return build_auth_resp(
            {"me": me, "scope": auth["scope"], "access_token": token}
        )

    # Token verification
    token = request.headers.get("Authorization").replace("Bearer ", "")
    try:
        payload = JWT.loads(token)
    except BadSignature:
        abort(403)

    # Check the token expritation (valid for 3 hours)
    if (datetime.now() - datetime.fromtimestamp(payload["ts"])) > timedelta(
        minutes=180
    ):
        abort(401)

    return build_auth_resp(
        {
            "me": payload["me"],
            "scope": " ".join(payload["scope"]),
            "client_id": payload["client_id"],
        }
    )

utils/__init__.py
import logging
from datetime import datetime
from datetime import timezone

from dateutil import parser
from little_boxes import activitypub as ap

logger = logging.getLogger(__name__)


def strtobool(s: str) -> bool:
    if s in ["y", "yes", "true", "on", "1"]:
        return True
    if s in ["n", "no", "false", "off", "0"]:
        return False

    raise ValueError(f"cannot convert {s} to bool")


def parse_datetime(s: str) -> datetime:
    # Parses the datetime with dateutil
    dt = parser.parse(s)

    # If no TZ is set, assumes it's UTC
    if not dt.tzinfo:
        dt = dt.replace(tzinfo=timezone.utc)

    return dt


def now() -> str:
    return ap.format_datetime(datetime.now(timezone.utc))

templates/admin.html
{% extends "layout.html" %}
{% import 'utils.html' as utils %}
{% block title %}Admin - {{ config.NAME }}{% endblock %}
{% block content %}
<div id="container">
{% include "header.html" %}
<div id="admin">
<h3>Admin</h3>
<h4>Links</h4>
<ul>
    <li><a href="/admin/indieauth">IndieAuth logs</a></li>
    <li><a href="/admin/tasks">Poussetaches tasks</a></li>
</ul>
<h4>DB</h4>
<ul>
	<li>Inbox size: <strong>{{ inbox_size }}</strong></li>
	<li>Outbox size: <strong>{{ outbox_size }}</strong></li>
</ul>
<h4>Collections</h4>
<ul>
	<li>followers: <strong>{{ col_followers }}</strong></li>
	<li>following: <strong>{{ col_following }}</strong></li>
	<li>liked: <strong>{{col_liked }}</strong></li>
</ul>
</div>

</div>
{% endblock %}

templates/direct_messages.html
{% extends "layout.html" %}
{% import 'utils.html' as utils %}
{% block title %}DMs - {{ config.NAME }}{% endblock %}
{% block header %}

{% endblock %}
{% block content %}
<div id="container">
<div id="direct_messages" style="margin-top:50px;">

    {% for thread in threads %}
    <h4><a class="lcolor" href="/admin/thread?oid={{thread.oid}}">With {{ ", ".join(thread.participants) }}</a>
        <small class="lcolor">{{ thread.len }} message{% if thread.len > 1 %}s{% endif %}</small>
    </h4>
	{{ utils.display_note(thread.last_reply.activity.object, meta=thread.last_reply.meta) }}
    {% endfor %}

</div>
</div>
{% endblock %}

templates/error.html
{% extends "layout.html" %}
{% import 'utils.html' as utils %}
{% block title %}{{code}} {{status_text}} - {{ config.NAME }}{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<div id="container">
{% if not request.path.startswith('/admin') %}
{% include "header.html" %}
{% endif %}
<main>
<h1>{{code}} {{status_text}}</h1>
<p>Something went wrong :(</p>
{% if tb %}
<div style="margin:50px 0;">
    <p>Please consider <a href="https://github.com/tsileo/microblog.pub/issues/new">opening an issue on GitHub</a>.<br>Here is the traceback:</p>
<code><pre>
{{ tb }}
</pre></code>
</div>
{% endif %}
</main>
</div>
{% endblock %}

templates/following.html
{% extends "layout.html" %}
{% import 'utils.html' as utils %}
{% block title %}Following - {{ config.NAME }}{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<div id="container">
{% include "header.html" %}

<div id="following">
	{% for (follow_id, meta) in following_data %}
    {% set follow = meta.object %}
    {% if session.logged_in %}
<div style="margin-left:90px;padding-bottom:5px;margin-bottom:15px;display:inline-block;">
<a class="bar-item" href="/admin/profile?actor_id={{follow.id}}">profile</a>
<form action="/api/undo" class="action-form"  method="post">
<input type="hidden" name="redirect" value="{{ request.path }}"/>
<input type="hidden" name="id" value="{{ follow_id }}"/>
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
<button type="submit" class="bar-item">unfollow</button>
</form>
{% if meta.notification_follows_back %}
<span class="bar-item-no-hover">follows you back</span>
{% endif %}

{% if lists %}
<form action="/api/add_to_list" class="action-form"  method="post">
<input type="hidden" name="redirect" value="{{ request.path }}"/>
<input type="hidden" name="actor_id" value="{{ follow.id }}"/>
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
<select name="list_name" style="float:left;">
<option></option>
{% for l in lists %}
{% if follow.id not in l.members %}
<option value="{{l.name}}">{{l.name}}</option>
{% endif %}
{% endfor %}
</select>
<button type="submit" class="bar-item">add to list</button>
</form>
{% endif %}

{% for l in lists %}
{% if follow.id in l.members %}
<form action="/api/remove_from_list" class="action-form"  method="post">
<input type="hidden" name="redirect" value="{{ request.path }}"/>
<input type="hidden" name="actor_id" value="{{ follow.id }}"/>
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
<button type="submit" class="bar-item">remove from {{ l.name }}</button>
</form>


{% endif %}
{% endfor %}

 
        </div>

    {% endif %}
    <div style="height: 100px;">
	{{ utils.display_actor_inline(follow, size=80) }}
    </div>
	{% endfor %}
    {{ utils.display_pagination(older_than, newer_than) }}
</div>

</div>
{% endblock %}
{% block links %}
<link rel="alternate" href="{{ config.BASE_URL }}/following" type="application/activity+json">
{{ utils.display_pagination_links(older_than, newer_than) }}{% endblock %}

templates/indieauth_flow.html
{% extends "layout.html" %}
{% import 'utils.html' as utils %}
{% block header %}
{% endblock %}
{% block content %}
<div style="width:90%;max-width: 720px;margin:40px auto;">

<div style="display:flex">
{% if client.logo %}
<div style="flex:initial;width:100px;">
<img src="{{client.logo}}" style="max-width:100px;">
</div>
{% endif %}
<div style="flex:1;">
<div style="margin-top:20px">
<a class="lcolor" style="font-size:1.2em;font-weight:600;text-decoration:none;" href="{{ client.url }}">{{ client.name }}</a>
<p>wants you to login as <strong class="lcolor">{{ me }}</strong></p>
</div>
</div>
</div>

<form method="POST" action="{{ url_for('indieauth.indieauth_flow') }}">
	{% if scopes %}
	<h3>Scopes</h3>
	<ul>
	{% for scope in scopes %}
	<li><input type="checkbox" name="scopes" value="{{scope}}" id="scope-{{scope}}"><label for="scope-{{scope}}">{{ scope }}</label>
	</li>
	{% endfor %}
	</ul>
	{% endif %}
	<input type="hidden" name="redirect_uri" value="{{ redirect_uri }}">
	<input type="hidden" name="state" value="{{ state }}">
	<input type="hidden" name="client_id" value="{{ client_id }}">
	<input type="hidden" name="me" value="{{ me }}">
	<input type="hidden" name="response_type" value="{{ response_type }}">
	<input type="submit" value="login">
</form>

</div>
{% endblock %}

templates/new.html
{% extends "layout.html" %}
{% import 'utils.html' as utils %}
{% block title %}New - {{ config.NAME }}{% endblock %}
{% block header %}

{% endblock %}
{% block content %}
<div id="container">
<div id="new">
{% if thread %}
<h3 style="padding-bottom: 30px">Replying to {{ content }}</h3>
{{ utils.display_thread(thread) }}
{% else %}
<div class="tabbar">
{% if request.args.get("question") == "1" %}
<a href="{{ url_for('admin.admin_new') }}" class="tab">Note</a><a href="{{ url_for('admin.admin_new') }}?question=1" class="tab selected">Question</a>
{% else %}
<a href="{{ url_for('admin.admin_new') }}" class="tab selected">Note</a><a href="{{ url_for('admin.admin_new') }}?question=1" class="tab">Question</a>
{% endif %}
</div>
{% endif %}
<form id="new-activity" action="/api/new_{% if request.args.get("question") == "1" %}question{%else%}note{%endif%}" method="POST" enctype="multipart/form-data">
<input type="hidden" name="redirect" value="/">
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
<select name="visibility" style="padding:8px 10px;">
{% for v in visibility %}
<option value="{{v.name}}" {% if v == default_visibility %}selected="selected"{% endif %}>{{ v.value }}</option>
{% endfor %}
</select>
{% if reply %}<input type="hidden" name="reply" value="{{reply}}">{% endif %}

<p><input type="text" name="summary" placeholder="summary/CW (optional)"></p>

<p>
{% for emoji in emojis %}
<span class="ji">{{ emoji | emojify | safe }}</span>
{% endfor %}
{% for emoji in custom_emojis %}
<span class="ji"><img src="{{emoji.get_icon_url()}}" alt="{{emoji.name}}" title="{{emoji.name}}" class="custom-emoji"></span>
{% endfor %}
</p>

<textarea name="content" rows="10" cols="50" autofocus="autofocus" designMode="on" style="font-size:1.2em;width:95%;">{{ content }}</textarea>

<p>
<input type="file" name="file">
<p>
<p>
<input type="text" name="file_description" placeholder="attachment description (optional)">
</p>

<p>
<input type="text" name="location_lat" id="location_lat" placeholder="latitude (optional)">
<input type="text" name="location_lng" id="location_lng" placeholder="longitude (optional)">
<a href="#" class="location_autofill">ask browser for location</a>
</p>
<p>
<input type="text" name="location_name" placeholder="location name (optional)">
</p>

{% if request.args.get("question") == "1" %}
<div style="margin-top:20px;">
    <p>Open for: <select name="open_for">
    <option value="5">5 minutes</option>
    <option value="10">10 minutes</option>
    <option value="15">15 minutes</option>
    <option value="30">30 minutes</option>
    <option value="60">1 hour</option>
    <option value="360">6 hour</option>
    <option value="1440" selected>1 day</option>
    <option value="4320">3 days</option>
    <option value="10080">7 days</option>
    </select></p>

    <p><select name="of">
        <option value="oneOf">Single choice</option>
        <option value="anyOf">Multiple choices</option>
    </select></p>

    {% for i in range(4) %}
    <p><input type="text" name="answer{{i}}" placeholder="Answer #{{i+1}}"></p>
    {% endfor %}

</div>
{% endif %}

<input type="submit" value="post">
</div>
</form>

</div>
</div>
<script nonce="{{ csp_nonce() }}">
// The new post textarea
var ta = document.getElementsByTagName("textarea")[0];
// Helper for inserting text (emojis) in the textarea
function insertAtCursor (textToInsert) {
    ta.focus();
    const isSuccess = document.execCommand("insertText", false, textToInsert);

    // Firefox (non-standard method)
    if (!isSuccess) {
        // Credits to https://www.everythingfrontend.com/posts/insert-text-into-textarea-at-cursor-position.html
        // get current text of the input
        const value = ta.value;
        // save selection start and end position
        const start = ta.selectionStart;
        const end = ta.selectionEnd;
        // update the value with our text inserted
        ta.value = value.slice(0, start) + textToInsert + value.slice(end);
        // update cursor to be at the end of insertion
        ta.selectionStart = ta.selectionEnd = start + textToInsert.length;
    }
}
// Emoji click callback func
var ji = function (ev) {
    insertAtCursor(ev.target.attributes.alt.value + " ");
    ta.focus()
    //console.log(document.execCommand('insertText', false /*no UI*/, ev.target.attributes.alt.value));
}
// Enable the click for each emojis
var items = document.getElementsByClassName("ji")
for (var i = 0; i < items.length; i++) {
    items[i].addEventListener('click', ji);
}
var askForLocation = function(ev) {
    ev.preventDefault();
    navigator.geolocation.getCurrentPosition(function(position) {
        document.getElementById("location_lat").value = position.coords.latitude;
        document.getElementById("location_lng").value = position.coords.longitude;
    });
}
var items = document.getElementsByClassName("location_autofill")
for (var i = 0; i < items.length; i++) {
    items[i].addEventListener('click', askForLocation);
}

</script>{% endblock %}

templates/remote_follow.html
{% extends "layout.html" %}
{% import 'utils.html' as utils %}
{% block header %}
{% endblock %}
{% block content %}
<div id="container">
{% include "header.html" %}
<main>
<h2 style="font-weight:normal">Remote follow @<span class="gold">{{ config.USERNAME }}</span>@<span class="gold">{{ config.DOMAIN }}</span></h2>

<form method="POST" action="">
	<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
	<input type="text" name="profile" placeholder="you@your-instance">
	<input type="submit" value="Follow">
</form>
</main>
</div>
{% endblock %}